## Build the docker code
## Push the docker image to docker hub
## ssh into the vm and start the new image

name: Deploy the backend
on: 
  push: 
     branches: [ main ]
jobs:
   build: 
      runs-on: ubuntu-latest
      steps: 
         - name: Checkout the code
           uses: actions/checkout@v2

         - name: Docker login
           uses: docker/login-action@v2
           with: 
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

         - name: Build and push
           uses: docker/build-push-action@v4
           with: 
             content: .
             file: ./docker/Dockerfile.backend
             push: true
             tags: sllik78/todo-app-backend:${{ github.sha }}

         - name: Deploy to the VM via SSH
           uses: appleboy/ssh-action@v1.0.0
           with: 
             host: ${{ secrets.VM_IP }}
             username: ubuntu
             key: ${{ secrets.SSH_PRIVATE_KEY_AWS }}
             script: |
                sudo docker pull sllik78/todo-app-backend:${{ github.sha }}
                sudo docker stop user_backend || true
                sudo docker rm user_backend || true
                sudo docker run -d --name user_backend -p 8080:8080 sllik78/todo-app-backend:${{ github.sha }}
