## Build the docker code
## Push the docker image to docker hub
## ssh into the vm and start the new image

name: Deploy the frontend
on: 
  push: 
     branches: [ main ]
jobs:
   build: 
      runs-on: ubuntu-latest
      steps: 
         - name: Checkout the code
           uses: actions/checkout@v2

         - name: Docker login
           uses: docker/login-action@v2
           with: 
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_PASSWORD }}

         - name: Build and push
           uses: docker/build-push-action@v4
           with: 
             content: .
             build-args: |
                - DATABASE_URL=${{ secrets.DATABASE_URL }}
             file: ./docker/Dockerfile.frontend
             push: true
             tags: sllik78/todo-app-frontend:${{ github.sha }}

        #  - name: Deploy to the VM
        #    run: 
